### ISSUE TITLE
[question] Is it possible to hook into the format action instead of/as well as the save action?

### ISSUE THREAD

**Issue by DazDotOne** [rohit-gohri/vscode-format-code-action#12]
Firstly, thanks for the awesome extension.

I'm a bit clueless with vscode extensions (and more generally the provided APIs) but was wondering if this could also hook into the format document command (default `shift+alt+f`) as well as save?

I tend to format my documents as I'm going then save after making progress, if I have added a lot of code since last saving, it can be a bit jarring having all of it formatted in one go.

**Comment by rohit-gohri** [comment]
The way this extension works is by registering a "Source Action" 

<img width="765" alt="image" src="https://user-images.githubusercontent.com/31949290/193040146-f8c51a27-160f-4477-a2f7-b26880d66a22.png">

<img width="352" alt="image" src="https://user-images.githubusercontent.com/31949290/193040086-3508c407-d92e-4f3a-a81c-fe20d1b1fd89.png">

So it can be triggered directly without save, but I don't know how to assign a keyboard shortcut to it. And even then it will have to be 2 commands triggered manually in order, First the Format Document one from this action and then "Fix all fixable eslint" source action. 

So I guess the answer would be no :/
