### ISSUE TITLE
Actions "Format Document" and "ESLint" looping on Save

### ISSUE THREAD

**Issue by alexmarles** [rohit-gohri/vscode-format-code-action#13]
Type: <b>Bug</b>

I have set `source.formatDocument` and `source.fixAll.eslint` as my actions to run on save (in this order). But since I last updated VSCode, everytime I save a file, it enters in a infinite loop, applying both formats one after the other.

settings.json 👇 
```
"editor.formatOnSave": false,
"editor.defaultFormatter": "esbenp.prettier-vscode",
"editor.codeActionsOnSave": [
        "source.formatDocument",
        "source.fixAll.eslint"
],
```

Effect 👇 
![Kapture 2022-11-08 at 13 21 28](https://user-images.githubusercontent.com/757181/200562421-a1f23bd3-67fa-4a12-b133-3bd20db64e59.gif)

Extension version: 0.1.0
VS Code version: Code 1.73.0 (Universal) (8fa188b2b301d36553cbc9ce1b0a146ccb93351f, 2022-11-01T15:38:50.881Z)
OS version: Darwin arm64 21.6.0
Modes:
Sandboxed: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Apple M1 Max (10 x 24)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: disabled_off<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_renderer: enabled_on<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: disabled_off|
|Load (avg)|9, 6, 6|
|Memory (System)|32.00GB (1.27GB free)|
|Process Argv|--crash-reporter-id d8f96fa4-5bb0-49bc-b585-6a97abc86e36|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vsreu685:30147344
python383:30185418
vspor879:30202332
vspor708:30202333
vspor363:30204092
vswsl492cf:30256860
vslsvsres303:30308271
pythonvspyl392:30443607
vserr242cf:30382550
pythontb:30283811
vsjup518:30340749
pythonptprofiler:30281270
vshan820:30294714
vstes263:30335439
vscorecescf:30445987
pythondataviewer:30285071
vscod805:30301674
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
cmake_vspar411:30581797
vsaa593cf:30376535
pythonvs932:30410667
cppdebug:30492333
vscaat:30438848
vsclangdf:30486550
c4g48928:30535728
dsvsc012:30540252
azure-dev_surveyone:30548225
pyindex848:30577860
nodejswelcome1:30587005
fc301958:30595537
282f8724:30602487
gswce2:30605431
3d0df643:30604793
dbltrim-noruby:30604474

```

</details>

**Comment by rohit-gohri** [comment]
This is a bug introduced in VS Code's latest release - https://github.com/microsoft/vscode/issues/165326 as pointed out by @sergioadimedia - [here](https://github.com/rohit-gohri/vscode-format-code-action/issues/7#issuecomment-1303384977) 

There is a workaround mentioned here - https://github.com/microsoft/vscode/issues/165326#issuecomment-1306194127

It seems, VS Code is not respecting `"editor.formatOnSave": false`

**Comment by alexmarles** [comment]
Got it, the workaround is working for me. Thank you!
