### ISSUE TITLE
VSCode Sept2023 release breaks this extension

### ISSUE THREAD

**Issue by Maxastuart** [rohit-gohri/vscode-format-code-action#14]
this no longer works: 

``` 
"editor.codeActionsOnSave": ["source.formatDocument", "source.fixAll.eslint"],
```

error msg: 
![image](https://github.com/rohit-gohri/vscode-format-code-action/assets/31591394/dd606fb0-5c1b-4fbe-b0ae-75613d2582d5)

forces me to use object notation: 
```
  "editor.codeActionsOnSave": {
    "source.organizeImports": "never",
    "source.formatDocument": "always",
    "source.fixAll.eslint": "always"
  },
```

...which breaks the order of the execution provided by the array 😭 😭 😭

**Comment by Maxastuart** [comment]
VSCode ver I was on today

Version: 1.83.0 (user setup)
Commit: e7e037083ff4455cf320e344325dacb480062c3c
Date: 2023-10-03T16:12:16.321Z
Electron: 25.8.4
ElectronBuildId: 24154031
Chromium: 114.0.5735.289
Node.js: 18.15.0
V8: 11.4.183.29-electron.0
OS: Windows_NT x64 10.0.22621

**Comment by rohit-gohri** [comment]
Thanks for reporting!
There is an open issue in VS Code - https://github.com/microsoft/vscode/issues/194861

They will add back support - https://github.com/microsoft/vscode/issues/194861#issuecomment-1749530806

**Comment by kferch-teamworks** [comment]
Arrays for codeactionsonsave were what allowed the "Format Code Action", rohit-gohri.format-code-action to work. This was important because the array determines the order which you can't do with an object. This was broken with 1.83 change to object.

**Comment by rohit-gohri** [comment]
Closing as VSCode issue (https://github.com/microsoft/vscode/issues/194861) is fixed
