### ISSUE TITLE
Format Only Modified Lines?

### ISSUE THREAD

**Issue by cojo** [rohit-gohri/vscode-format-code-action#5]
Hi,

Thanks for this plugin, solves some major issues we were having with import organization issues between prettier and VSCode and lots of pain as a result.

That said, I was wondering if you might consider adding an option for only formatting modified lines?  I have previously set `editor.formatOnSaveMode` to `modifications` which causes it to use the `Format Modified Lines` command instead per: https://github.com/microsoft/vscode/issues/44075#issuecomment-678227183 - not sure what the best way to integrate it here would be, but it would be nice to have the option to not have to format the whole document every time now in order to use this plugin / get the fixes it provides elsewhere.

Thanks again!

**Comment by CoLdAs1cE** [comment]
@rohit-gohri when do this go live? :D
in dire need

**Comment by rohit-gohri** [comment]
There were some bugs with the implementation, will try to at least release a beta for testing purposes by the weekend. So I can collect some feedback.

**Comment by rohit-gohri** [comment]
If anyone has experience with extension development, I would appreciate their review a on the PR (#6)

**Comment by cojo** [comment]
Reviewed! I'm not the most experienced with extension development but it all made sense / looked good to me.

**Comment by rohit-gohri** [comment]
Sorry for the delays, have finally released the feature. I haven't personally used formatModified before so not sure if the behavior is 100% correct. Let me know if you face any problems

**Comment by CoLdAs1cE** [comment]
a quick test without eslint seems to be working

**Comment by rohit-gohri** [comment]
Closing this now. If anyone faces any new problems, feel free to open a new issue. 

And, thanks for the PR review @cojo 👍

**Comment by CoLdAs1cE** [comment]
@rohit-gohri not sure if this i should create a new issue but
![image](https://user-images.githubusercontent.com/1981573/107134582-bd778380-68f3-11eb-8369-7b8837f72bd9.png)
![image](https://user-images.githubusercontent.com/1981573/107134592-d2541700-68f3-11eb-9242-a967275efd48.png)
![image](https://user-images.githubusercontent.com/1981573/107134642-2f4fcd00-68f4-11eb-98c8-f054caa60dc5.png)

when i use formatModified. but it does its job fixes eslint errors, but quite annoying

**Comment by rohit-gohri** [comment]
@CoLdAs1cE It'll be great if you could open a new issue with a small code sample that triggers this and your eslint & prettier configs.

**Comment by rohit-gohri** [comment]
@CoLdAs1cE the error could be because prettier extension itself doesn't support formatModified maybe? https://github.com/prettier/prettier-vscode/issues/1677

**Comment by CoLdAs1cE** [comment]
> 
> 
> @CoLdAs1cE the error could be because prettier extension itself doesn't support formatModified maybe? [prettier/prettier-vscode#1677](https://github.com/prettier/prettier-vscode/issues/1677)

I did ask, they say it saves on modified

**Comment by rohit-gohri** [comment]
> UPDATE:
> Wow i had the old version and could not get this to work at the time so i was switching back and forth between prettier and this, so i had on format on save which gives this error 😞

So, working now I guess?

**Comment by CoLdAs1cE** [comment]
Yeah, sorry about unclear answer :P
